service: fastaf-website
plugins:
  - serverless-s3-sync

provider:
  name: aws
  runtime: nodejs8.10
  region: us-east-1

custom:
  s3Sync:
    - bucketName: long.af
      localDir: dist

resources:
  Resources:
    AssetsBucket:
      Type: AWS::S3::Bucket
      Properties:
        BucketName: long.af
